### ISSUE TITLE
AvformatOpenInput with Dictionary crash

### ISSUE THREAD

**Issue by iniwf** [giorgisio/goav#57]
os: ubuntu 18.04.2
golang:1.12
ffmpeg:4.1.3

**code:**
fmtCtx := avformat.AvformatAllocContext()
d := &avutil.Dictionary{}
d.AvDictSet("rtsp_transport", "tcp", 0)
d.AvDictSet("stimeout", "2000000", 0)
if avformat.AvformatOpenInput(&fmtCtx, "", nil, &d) != 0 {
	return errors.New(fmt.Sprintf("Unable to open video url %s\n", videoUrl))
}

**crash log:**
free(): invalid pointer
SIGABRT: abort
PC=0x7ff3043c8e97 m=4 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7ff3043c8e97
stack: frame={sp:0x7ff2fd70d980, fp:0x0} stack=[0x7ff2fcf0e288,0x7ff2fd70de88)
00007ff2fd70d880:  0000000000000000  0000000000000000 
00007ff2fd70d890:  0000000000000000  0000000000000000 
00007ff2fd70d8a0:  0000000000000000  0000000000000000 
00007ff2fd70d8b0:  0000000000000000  0000000000000000 
00007ff2fd70d8c0:  0000000000000000  0000000000000000 
00007ff2fd70d8d0:  0000000000000000  0000000000000000 
00007ff2fd70d8e0:  0000000000000000  0000000000000000 
00007ff2fd70d8f0:  0000000000000000  0000000000000000 
00007ff2fd70d900:  6e203a65676e6152  3030302e303d7470 
00007ff2fd70d910:  00000000000a0d2d  0000ffff00001fb2 
00007ff2fd70d920:  0000000000000005  0000000000000000 
00007ff2fd70d930:  0000000000000001  00007ff3068b6170 
00007ff2fd70d940:  00000000004398f9  0000000100015330 
00007ff2fd70d950:  00007ff2fd70d980  00007ff2fd70d990 
00007ff2fd70d960:  0000000001bf41c5  0000000001e08b10 
00007ff2fd70d970:  0000000001e08b1e  0000000001e66aa8 
00007ff2fd70d980: <0000000000000000  0000000000000000 
00007ff2fd70d990:  31332e3836312e32  3435353a3838312e 
00007ff2fd70d9a0:  0000000000000000  0000000000000000 
00007ff2fd70d9b0:  0000000000000000  0000000000000000 
00007ff2fd70d9c0:  74756f656d697473  00007ff2f4000000 
00007ff2fd70d9d0:  74756f656d697473  00007ff2f4000000 
00007ff2fd70d9e0:  0000000000000000  0000000000000035 
00007ff2fd70d9f0:  0000000000000000  0000000000000000 
00007ff2fd70da00:  fffffffe7fffffff  ffffffffffffffff 
00007ff2fd70da10:  ffffffffffffffff  ffffffffffffffff 
00007ff2fd70da20:  ffffffffffffffff  ffffffffffffffff 
00007ff2fd70da30:  ffffffffffffffff  ffffffffffffffff 
00007ff2fd70da40:  ffffffffffffffff  ffffffffffffffff 
00007ff2fd70da50:  ffffffffffffffff  ffffffffffffffff 
00007ff2fd70da60:  ffffffffffffffff  ffffffffffffffff 
00007ff2fd70da70:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7ff3043c8e97
stack: frame={sp:0x7ff2fd70d980, fp:0x0} stack=[0x7ff2fcf0e288,0x7ff2fd70de88)
00007ff2fd70d880:  0000000000000000  0000000000000000 
00007ff2fd70d890:  0000000000000000  0000000000000000 
00007ff2fd70d8a0:  0000000000000000  0000000000000000 
00007ff2fd70d8b0:  0000000000000000  0000000000000000 
00007ff2fd70d8c0:  0000000000000000  0000000000000000 
00007ff2fd70d8d0:  0000000000000000  0000000000000000 
00007ff2fd70d8e0:  0000000000000000  0000000000000000 
00007ff2fd70d8f0:  0000000000000000  0000000000000000 
00007ff2fd70d900:  6e203a65676e6152  3030302e303d7470 
00007ff2fd70d910:  00000000000a0d2d  0000ffff00001fb2 
00007ff2fd70d920:  0000000000000005  0000000000000000 
00007ff2fd70d930:  0000000000000001  00007ff3068b6170 
00007ff2fd70d940:  00000000004398f9  0000000100015330 
00007ff2fd70d950:  00007ff2fd70d980  00007ff2fd70d990 
00007ff2fd70d960:  0000000001bf41c5  0000000001e08b10 
00007ff2fd70d970:  0000000001e08b1e  0000000001e66aa8 
00007ff2fd70d980: <0000000000000000  0000000000000000 
00007ff2fd70d990:  31332e3836312e32  3435353a3838312e 
00007ff2fd70d9a0:  0000000000000000  0000000000000000 
00007ff2fd70d9b0:  0000000000000000  0000000000000000 
00007ff2fd70d9c0:  74756f656d697473  00007ff2f4000000 
00007ff2fd70d9d0:  74756f656d697473  00007ff2f4000000 
00007ff2fd70d9e0:  0000000000000000  0000000000000035 
00007ff2fd70d9f0:  0000000000000000  0000000000000000 
00007ff2fd70da00:  fffffffe7fffffff  ffffffffffffffff 
00007ff2fd70da10:  ffffffffffffffff  ffffffffffffffff 
00007ff2fd70da20:  ffffffffffffffff  ffffffffffffffff 
00007ff2fd70da30:  ffffffffffffffff  ffffffffffffffff 
00007ff2fd70da40:  ffffffffffffffff  ffffffffffffffff 
00007ff2fd70da50:  ffffffffffffffff  ffffffffffffffff 
00007ff2fd70da60:  ffffffffffffffff  ffffffffffffffff 
00007ff2fd70da70:  ffffffffffffffff  ffffffffffffffff 

goroutine 1 [syscall]:
runtime.cgocall(0xbc8eb0, 0xc000241c68, 0x4f9078)
	/usr/lib/go-1.12/src/runtime/cgocall.go:128 +0x5b fp=0xc000241c38 sp=0xc000241c00 pc=0x4f009b
github.com/giorgisio/goav/avformat._Cfunc_avformat_open_input(0xc000010bf0, 0x7ff2f4002690, 0x0, 0xc000010bf8, 0x0)
	_cgo_gotypes.go:2311 +0x4d fp=0xc000241c68 sp=0xc000241c38 pc=0x5fd24d
github.com/giorgisio/goav/avformat.AvformatOpenInput.func2(0xc000010bf0, 0x7ff2f4002690, 0x0, 0xc000010bf8, 0xc00009c000)
	/home/iniwf/iniwf/gopath/src/github.com/giorgisio/goav/avformat/avformat.go:191 +0xce fp=0xc000241ca0 sp=0xc000241c68 pc=0x60024e
github.com/giorgisio/goav/avformat.AvformatOpenInput(0xc000010bf0, 0x1a7cf56, 0x2a, 0x0, 0xc000010bf8, 0x0)
	/home/iniwf/iniwf/gopath/src/github.com/giorgisio/goav/avformat/avformat.go:191 +0x91 fp=0xc000241ce0 sp=0xc000241ca0 pc=0x5fd9e1
light-ivs/ivs.(*FaceEngine).SaveVideo(0xc000241f50, 0x1a7cf56, 0x2a, 0x1, 0x1)

**Comment by mrpep80** [comment]
same issue

**Comment by mrpep80** [comment]
I have the same problem and I try a deep analisys with kdbg

os: Ubuntu 18.04.2 LTS
golang: 1.12.7 linux/amd64
ffmpeg: version N-94405-g43891ea8ab

    dict := &avutil.Dictionary{}
    dict.AvDictSet("rtsp_transport", "tcp", 0)
    fmt.Printf("DICT : NUM ELEMENTI = %d\n", i dict.AvDictCount()) 
    dict.AvDictSet("allowed_media_types", "video", 0)  <------------------crash is here
    if avformat.AvformatOpenInput(&ctx, filename, nil, &dict) != 0 {
        log.Println("Error: Couldn't open file.")
        return
    }


    fatal error: unexpected signal during runtime execution
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x102bbe3ba pc=0x1481df5]
    runtime stack:
    runtime.throw(0x15295ce, 0x2a)
    /snap/go/4098/src/runtime/panic.go:617 +0x72 
    runtime.sigpanic()
    /snap/go/4098/src/runtime/signal_unix.go:374 +0x4a9

    goroutine 1 [syscall]: runtime.cgocall(0x4f5a51, 0xc00004be88, 0xc00004be90)
        /snap/go/4098/src/runtime/cgocall.go:128 +0x5b fp=0xc00004be58 sp=0xc00004be20   pc=0x45c2bb
    github.com/giorgisio/goav/avutil._Cfunc_av_dict_set(0xc0000100a0, 0x2bbe3e0, 0x2bbe400, 0x0, 0x0)
    _cgo_gotypes.go:380 +0x4d fp=0xc00004be88 sp=0xc00004be58 pc=0x4eeccd
    github.com/giorgisio/goav/avutil.(*Dictionary).AvDictSet.func1(0xc0000100a0, 0x2bbe3e0, 0x2bbe400, 0x0, 0x18)
    ...../goLang/src/github.com/giorgisio/goav/avutil/dict.go:63 +0x73 fp=0xc00004bec0 sp=0xc00004be88 pc=0x4ef053
    github.com/giorgisio/goav/avutil.(*Dictionary).AvDictSet(0x2445ed0, 0x15252d5, 0x13, 0x152347b, 0x5, 0x0, 0x1)
        ...../goLang/src/github.com/giorgisio/goav/avutil/dict.go:63 +0xa8 fp=0xc00004bf08  sp=0xc00004bec0 pc=0x4eef38
    main.main()
        ...../goLang/src/hello/main.go:35 +0x1bd fp=0xc00004bf98 sp=0xc00004bf08 pc=0x4f321d
    runtime.main()
        /snap/go/4098/src/runtime/proc.go:200 +0x20c fp=0xc00004bfe0 sp=0xc00004bf98  pc=0x4838cc
    runtime.goexit()
        /snap/go/4098/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00004bfe8 sp=0xc00004bfe0 pc=0x4ab2e1

debug with kdbg i have seen that the pointer to the dictionary area is overwritten 
If I don't call the "AvDictCount" I have another problem (double free)

**Comment by ailumiyana** [comment]
I have met the same problem.
Could anyone give some advice?

os: Ubuntu 19.04
golang: go1.12.10 linux/amd64
ffmpeg version N-94335-g9869e2177

double free or corruption (out)
SIGABRT: abort
PC=0x7f3a6082aed7 m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f3a6082aed7
stack: frame={sp:0x7fff8f1abb70, fp:0x0} stack=[0x7fff8e9ad228,0x7fff8f1ac250)
00007fff8f1aba70:  0000000000000000  000000000227fbc0 
00007fff8f1aba80:  00000000ffffffff  00007fff8f1abae8 
00007fff8f1aba90:  00007f3a60cc3030  00007f3a623509f0 
00007fff8f1abaa0:  00007f3a60cc5c25  0000000000000017 
00007fff8f1abab0:  00007f3a0000000a  0000000000000000 
00007fff8f1abac0:  00007f3a001e8480  00000000001e8480 
00007fff8f1abad0:  0000000400000003  00007f3a619028e8 
00007fff8f1abae0:  00007f3a61926ea0  000000c0000100a8 
00007fff8f1abaf0:  0000000000000000  00007fff8f1abf68 
00007fff8f1abb00:  0000000000000001  00007f3a6236c0c0 
00007fff8f1abb10:  0000000000000005  0000000000000000 
00007fff8f1abb20:  000000000222b900  00007f3a60cc3030 
00007fff8f1abb30:  00007fff8f1abf30  00007f3a6237327a 
00007fff8f1abb40:  0000000000000000  0000000000000000 
00007fff8f1abb50:  00007f3a61fcd500  0000000000000000 
00007fff8f1abb60:  000000c0000100a8  0000000000000000 
00007fff8f1abb70: <0000000000000000  00007f3a6167ef6a 
00007fff8f1abb80:  00007f3a6165fcef  00007f3a6167ef6e 
00007fff8f1abb90:  00007f3a6167ef72  0000ffff00001fa0 
00007fff8f1abba0:  00007f3a6167ef76  00007f3a6167ef7a 
00007fff8f1abbb0:  00007f3a615e70d5  00007f3a6167ef7e 
00007fff8f1abbc0:  00007f3a6167ef82  00007f3a60d21822 
00007fff8f1abbd0:  00007f3a60d1f864  00007f3a60d1f868 
00007fff8f1abbe0:  00007f3a60d2173a  00007f3a60d1ecc9 
00007fff8f1abbf0:  fffffffe7fffffff  ffffffffffffffff 
00007fff8f1abc00:  ffffffffffffffff  ffffffffffffffff 
00007fff8f1abc10:  ffffffffffffffff  ffffffffffffffff 
00007fff8f1abc20:  ffffffffffffffff  ffffffffffffffff 
00007fff8f1abc30:  ffffffffffffffff  ffffffffffffffff 
00007fff8f1abc40:  ffffffffffffffff  ffffffffffffffff 
00007fff8f1abc50:  ffffffffffffffff  ffffffffffffffff 
00007fff8f1abc60:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7f3a6082aed7
stack: frame={sp:0x7fff8f1abb70, fp:0x0} stack=[0x7fff8e9ad228,0x7fff8f1ac250)
00007fff8f1aba70:  0000000000000000  000000000227fbc0 
00007fff8f1aba80:  00000000ffffffff  00007fff8f1abae8 
00007fff8f1aba90:  00007f3a60cc3030  00007f3a623509f0 
00007fff8f1abaa0:  00007f3a60cc5c25  0000000000000017 
00007fff8f1abab0:  00007f3a0000000a  0000000000000000 
00007fff8f1abac0:  00007f3a001e8480  00000000001e8480 
00007fff8f1abad0:  0000000400000003  00007f3a619028e8 
00007fff8f1abae0:  00007f3a61926ea0  000000c0000100a8 
00007fff8f1abaf0:  0000000000000000  00007fff8f1abf68 
00007fff8f1abb00:  0000000000000001  00007f3a6236c0c0 
00007fff8f1abb10:  0000000000000005  0000000000000000 
00007fff8f1abb20:  000000000222b900  00007f3a60cc3030 
00007fff8f1abb30:  00007fff8f1abf30  00007f3a6237327a 
00007fff8f1abb40:  0000000000000000  0000000000000000 
00007fff8f1abb50:  00007f3a61fcd500  0000000000000000 
00007fff8f1abb60:  000000c0000100a8  0000000000000000 
00007fff8f1abb70: <0000000000000000  00007f3a6167ef6a 
00007fff8f1abb80:  00007f3a6165fcef  00007f3a6167ef6e 
00007fff8f1abb90:  00007f3a6167ef72  0000ffff00001fa0 
00007fff8f1abba0:  00007f3a6167ef76  00007f3a6167ef7a 
00007fff8f1abbb0:  00007f3a615e70d5  00007f3a6167ef7e 
00007fff8f1abbc0:  00007f3a6167ef82  00007f3a60d21822 
00007fff8f1abbd0:  00007f3a60d1f864  00007f3a60d1f868 
00007fff8f1abbe0:  00007f3a60d2173a  00007f3a60d1ecc9 
00007fff8f1abbf0:  fffffffe7fffffff  ffffffffffffffff 
00007fff8f1abc00:  ffffffffffffffff  ffffffffffffffff 
00007fff8f1abc10:  ffffffffffffffff  ffffffffffffffff 
00007fff8f1abc20:  ffffffffffffffff  ffffffffffffffff 
00007fff8f1abc30:  ffffffffffffffff  ffffffffffffffff 
00007fff8f1abc40:  ffffffffffffffff  ffffffffffffffff 
00007fff8f1abc50:  ffffffffffffffff  ffffffffffffffff 
00007fff8f1abc60:  ffffffffffffffff  ffffffffffffffff 

goroutine 1 [syscall]:
runtime.cgocall(0x674140, 0xc0000bbc58, 0x0)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc0000bbc28 sp=0xc0000bbbf0 pc=0x40d3bb
ffmpeg-server/goav/avcodec._Cfunc_avcodec_open2(0x227f740, 0x7f3a61926ea0, 0xc0000100a8, 0x0)
	_cgo_gotypes.go:2692 +0x4d fp=0xc0000bbc58 sp=0xc0000bbc28 pc=0x4ccb4d
ffmpeg-server/goav/avcodec.(*Context).AvcodecOpen2.func1(0x227f740, 0x7f3a61926ea0, 0xc0000100a8, 0x0)
	/home/sola/server_sources/mcu-servers/ffmpeg-server/goav/avcodec/context.go:117 +0xc4 fp=0xc0000bbc90 sp=0xc0000bbc58 pc=0x4cd324
ffmpeg-server/goav/avcodec.(*Context).AvcodecOpen2(0x227f740, 0x7f3a61926ea0, 0xc0000100a8, 0x1)
	/home/sola/server_sources/mcu-servers/ffmpeg-server/goav/avcodec/context.go:117 +0x3f fp=0xc0000bbcc0 sp=0xc0000bbc90 pc=0x4ccfaf
main.decode_encode()
	/home/sola/server_sources/mcu-servers/ffmpeg-server/unit_test/vaapi-test.go:220 +0x533 fp=0xc0000bbf80 sp=0xc0000bbcc0 pc=0x672053
main.main()
	/home/sola/server_sources/mcu-servers/ffmpeg-server/unit_test/vaapi-test.go:668 +0x2f fp=0xc0000bbf98 sp=0xc0000bbf80 pc=0x672f7f
runtime.main()
	/usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc0000bbfe0 sp=0xc0000bbf98 pc=0x4375dc
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000bbfe8 sp=0xc0000bbfe0 pc=0x4613f1

rax    0x0
rbx    0x7fff8f1abde0
rcx    0x7f3a6082aed7
rdx    0x0
rdi    0x2
rsi    0x7fff8f1abb70
rbp    0x7fff8f1abec0
rsp    0x7fff8f1abb70
r8     0x0
r9     0x7fff8f1abb70
r10    0x8
r11    0x246
r12    0x7fff8f1abde0
r13    0x1000
r14    0x7f3a54bc0000
r15    0x20
rip    0x7f3a6082aed7
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
exit status 2

**Comment by ailumiyana** [comment]
> I have met the same problem.
> Could anyone give some advice?
> 
> os: Ubuntu 19.04
> golang: go1.12.10 linux/amd64
> ffmpeg version N-94335-g9869e2177
> 
> code :
> var dict *avutil.Dictionary = &avutil.Dictionary{}
> er := dict.AvDictSet("profile", "main", 0)
> if er < 0 {
> log.Critical("AvDictSet failed")
> return
> }
> er = dict.AvDictSet("level", "62", 0)
> if er < 0 {
> log.Critical("AvDictSet failed")
> return
> }
> fmt.Println(dict.AvDictCount())
> fmt.Println(dict.AvDictGet("profile", nil, 0))
> fmt.Println(dict.AvDictGet("level", nil, 0))
> 
> ```
> err = context_enc.AvcodecOpen2(codec_enc, (**avcodec.Dictionary)(unsafe.Pointer(&dict)))
> if err < 0 {
> 	log.Critical("AvcodecOpen2 failed.")
> 	return
> }
> ```
> 
> double free or corruption (out)
> SIGABRT: abort
> PC=0x7f3a6082aed7 m=0 sigcode=18446744073709551610

---------------------------------------------------------------------------------

oh, I have added a function then  erverthing works :

//#include <libavutil/avutil.h>
//#include <libavutil/dict.h>

int avcodec_open2_native(AVCodecContext* ctxt, AVCodec* c, AVDictionary** d) {
	if (d != NULL) {
		AVDictionary *tmp = NULL;
		av_dict_copy(&tmp, *d, 0);

		return avcodec_open2(ctxt, c, &tmp);
	} else {
		return avcodec_open2(ctxt, c, NULL);
	}
}

//Initialize the Context to use the given Codec
func (ctxt *Context) AvcodecOpen2(c *Codec, d **Dictionary) int {
	//return int(C.avcodec_open2((*C.struct_AVCodecContext)(ctxt), (*C.struct_AVCodec)(c), (**C.struct_AVDictionary)(unsafe.Pointer(d))))
	return int(C.avcodec_open2_native((*C.struct_AVCodecContext)(ctxt), (*C.struct_AVCodec)(c), (**C.struct_AVDictionary)(unsafe.Pointer(d))))
}

**Comment by ailumiyana** [comment]
> > I have met the same problem.
> > Could anyone give some advice?
> > os: Ubuntu 19.04
> > golang: go1.12.10 linux/amd64
> > ffmpeg version N-94335-g9869e2177
> > code :
> > var dict *avutil.Dictionary = &avutil.Dictionary{}
> > er := dict.AvDictSet("profile", "main", 0)
> > if er < 0 {
> > log.Critical("AvDictSet failed")
> > return
> > }
> > er = dict.AvDictSet("level", "62", 0)
> > if er < 0 {
> > log.Critical("AvDictSet failed")
> > return
> > }
> > fmt.Println(dict.AvDictCount())
> > fmt.Println(dict.AvDictGet("profile", nil, 0))
> > fmt.Println(dict.AvDictGet("level", nil, 0))
> > ```
> > err = context_enc.AvcodecOpen2(codec_enc, (**avcodec.Dictionary)(unsafe.Pointer(&dict)))
> > if err < 0 {
> > 	log.Critical("AvcodecOpen2 failed.")
> > 	return
> > }
> > ```
> > 
> > 
> > double free or corruption (out)
> > SIGABRT: abort
> > PC=0x7f3a6082aed7 m=0 sigcode=18446744073709551610
> 
> oh, I have added a function then erverthing works :
> 
> ```c
> //#include <libavutil/avutil.h>
> //#include <libavutil/dict.h>
> 
> int avcodec_open2_native(AVCodecContext* ctxt, AVCodec* c, AVDictionary** d) {
> 	if (d != NULL) {
> 		AVDictionary *tmp = NULL;
> 		av_dict_copy(&tmp, *d, 0);
> 
> 		return avcodec_open2(ctxt, c, &tmp);
> 	} else {
> 		return avcodec_open2(ctxt, c, NULL);
> 	}
> }
> 
> //Initialize the Context to use the given Codec
> func (ctxt *Context) AvcodecOpen2(c *Codec, d **Dictionary) int {
> 	//return int(C.avcodec_open2((*C.struct_AVCodecContext)(ctxt), (*C.struct_AVCodec)(c), (**C.struct_AVDictionary)(unsafe.Pointer(d))))
> 	return int(C.avcodec_open2_native((*C.struct_AVCodecContext)(ctxt), (*C.struct_AVCodec)(c), (**C.struct_AVDictionary)(unsafe.Pointer(d))))
> }
> ```


a way to fix up dictionary crash : 
just add an alloc func : 

```go
+/*struct AVDictionary {
+    int count;
+    AVDictionaryEntry *elems;
+};
+
+AVDictionary* av_dict_alloc() {
+	AVDictionary *d;
+	d = av_mallocz(sizeof(struct AVDictionary));
+	d->elems = av_mallocz(sizeof(AVDictionaryEntry));
+
+	return d;
+}*/
import "C"

+func AvDictAlloc() *Dictionary {
+	return (*Dictionary)(C.av_dict_alloc())
+}
```

```go
	var dict *avutil.Dictionary = avutil.AvDictAlloc()
	er := dict.AvDictSet("profile", "constrained_baseline", 0)
	if er < 0 {
		log.Critical("AvDictSet failed")
		return 
	}
	er = dict.AvDictSet("level", "52", 0)
	if er < 0 {
		log.Critical("AvDictSet failed")
		return 
	}

	fmt.Println(dict.AvDictCount())
	//fmt.Println(dict.AvDictGet("profile", nil, 0))
	//fmt.Println(dict.AvDictGet("level", nil, 0))
	//dict.AvDictFree()

	err = context_enc.AvcodecOpen2(codec_enc, (**avcodec.Dictionary)(unsafe.Pointer(&dict)))
	if err < 0 {
		log.Critical("AvcodecOpen2 failed.")
		return
	}
```
